<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRmhmk6w\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRmhmk6w/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRmhmk6w.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRmhmk6w\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRmhmk6w\appProdProjectContainer(array(
    'container.build_hash' => 'Rmhmk6w',
    'container.build_id' => 'a5f56a0a',
    'container.build_time' => 1517230392,
));
