<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJy54tnz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJy54tnz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJy54tnz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJy54tnz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJy54tnz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jy54tnz',
    'container.build_id' => 'e00c497f',
    'container.build_time' => 1522069412,
));
