<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3r0mzvq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3r0mzvq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3r0mzvq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3r0mzvq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3r0mzvq\appDevDebugProjectContainer(array(
    'container.build_hash' => '3r0mzvq',
    'container.build_id' => '60dbea2c',
    'container.build_time' => 1522064522,
));
